test_args:
  score_fusion_mode: [embedding_only]

test_dataset:
  trial_dataset: SPOOFCELEB_Validation SPOOFCELEB_Test ITW
  batch_size: 1 # unused parameter, always 1
  num_workers: 0  # unused parameter, always 0
  pin_memory: True
  prefetch_factor: # unused parameter, always None

preprocessing:
  duration: 2 # For evaluation this is internally -1, so no fixed duration during evaluation
  sample_rate: 16000
  silence_threshold: 30
  remove_leading_trailing_silence: True
  remove_all_silence: False

frontend:
  model_name: fbank
  model_args:
    sample_rate: 16000
    n_mels: 80
    dither: 0
    mean_norm: True

backend:
  model_name: ECAPA_TDNN_GLOB_c1024
  model_args:
    feat_dim: 80
    embed_dim: 192
  checkpoint_path: 'Pretrained_Models_WeSpeaker/voxceleb_ECAPA1024_LM/avg_model.pt'